language: erlang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq 
  - sudo apt-get install -qq sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git
  - ./launch.sh install

script: 
  - luac -p bot/*.lua
  - luac -p plugins/*.lua